name: flutter_matrix_of_skills
description: Flutter project disgned to simplify performance tracking of students and workers

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  curved_navigation_bar: ^1.0.3
  http: ^0.13.5
  url_launcher: ^6.1.6
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  flutter_secure_storage: ^6.0.0
  flutter_native_splash: ^2.2.14
  supabase_flutter: ^1.1.0
  flutter_launcher_icons: ^0.10.0
  syncfusion_flutter_charts: ^20.3.56
  fl_chart: ^0.55.2
  uni_links_desktop: ^0.1.3
  bitsdojo_window: ^0.1.5
  uni_links: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter_icons:
  image_path: "assets/core/images/logo_round.png"
  android: true
  ios: true

flutter_native_splash:
  image: assets/core/images/splashscreen_logo.png
  color: "#FFFFFF"
flutter:

  uses-material-design: true

  assets:
    - assets/core/images/