name: flutter_matrix_of_skills
description: Flutter project disgned to simplify performance tracking of students and workers

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  curved_navigation_bar: ^1.0.3
  http: ^0.13.5
  url_launcher: ^6.1.5
  bloc: ^8.1.0
  flutter_bloc: ^8.0.1
  flutter_secure_storage: ^5.1.0
  flutter_native_splash: ^2.2.7
  supabase_flutter: ^0.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true
